version: '3.8'

services:
  weaviate:
    image: semitechnologies/weaviate:1.21.0
    ports:
      - "8080:8080"
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
    volumes:
      - ./weaviate_data:/var/lib/weaviate

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
